INFO 2023-12-12 15:47:07,909 autoreload 23244 18936 Watching for file changes with StatReloader
INFO 2023-12-12 15:47:11,177 autoreload 23244 18936 D:\GB\TASKS\Django\sem3\sem3app\models.py changed, reloading.
INFO 2023-12-12 15:47:11,683 autoreload 16220 14212 Watching for file changes with StatReloader
INFO 2023-12-12 15:51:42,289 autoreload 16220 14212 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 15:51:42,762 autoreload 11692 13792 Watching for file changes with StatReloader
INFO 2023-12-12 15:52:23,635 autoreload 11692 13792 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 15:52:24,172 autoreload 22676 23072 Watching for file changes with StatReloader
WARNING 2023-12-12 15:52:41,008 log 22676 5696 Not Found: /sem3app/
WARNING 2023-12-12 15:52:41,008 basehttp 22676 5696 "GET /sem3app/ HTTP/1.1" 404 2583
WARNING 2023-12-12 15:52:41,111 log 22676 5696 Not Found: /favicon.ico
INFO 2023-12-12 15:52:41,112 basehttp 22676 5696 - Broken pipe from ('127.0.0.1', 50288)
INFO 2023-12-12 15:55:55,590 autoreload 22676 23072 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 15:55:56,062 autoreload 16460 15444 Watching for file changes with StatReloader
INFO 2023-12-12 15:57:39,953 autoreload 16460 15444 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 15:57:40,297 autoreload 12556 8688 Watching for file changes with StatReloader
INFO 2023-12-12 15:57:55,472 basehttp 12556 17816 "GET /sem3app/ HTTP/1.1" 200 53
WARNING 2023-12-12 15:57:55,600 log 12556 17816 Not Found: /favicon.ico
INFO 2023-12-12 15:57:55,600 basehttp 12556 17816 - Broken pipe from ('127.0.0.1', 50643)
INFO 2023-12-12 16:00:54,342 autoreload 12556 8688 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 16:00:54,755 autoreload 24592 5920 Watching for file changes with StatReloader
INFO 2023-12-12 16:01:12,101 basehttp 24592 5140 "GET /sem3app/ HTTP/1.1" 200 143
WARNING 2023-12-12 16:01:12,187 log 24592 5140 Not Found: /favicon.ico
INFO 2023-12-12 16:01:12,187 basehttp 24592 5140 - Broken pipe from ('127.0.0.1', 50769)
INFO 2023-12-12 16:05:28,388 autoreload 24592 5920 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 16:05:28,836 autoreload 7344 5524 Watching for file changes with StatReloader
INFO 2023-12-12 16:07:19,068 autoreload 7344 5524 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 16:07:19,471 autoreload 15112 11124 Watching for file changes with StatReloader
INFO 2023-12-12 16:07:19,888 basehttp 15112 16720 "GET /sem3app/ HTTP/1.1" 200 228
WARNING 2023-12-12 16:07:19,973 log 15112 16720 Not Found: /favicon.ico
INFO 2023-12-12 16:07:19,973 basehttp 15112 16720 - Broken pipe from ('127.0.0.1', 51103)
INFO 2023-12-12 16:07:40,012 autoreload 15112 11124 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 16:07:40,429 autoreload 3692 25096 Watching for file changes with StatReloader
INFO 2023-12-12 16:07:41,395 basehttp 3692 22508 "GET /sem3app/ HTTP/1.1" 200 225
WARNING 2023-12-12 16:09:54,464 log 3692 10304 Not Found: /
WARNING 2023-12-12 16:09:54,464 basehttp 3692 10304 "GET / HTTP/1.1" 404 2165
WARNING 2023-12-12 16:09:54,550 log 3692 10304 Not Found: /favicon.ico
INFO 2023-12-12 16:09:54,550 basehttp 3692 10304 - Broken pipe from ('127.0.0.1', 51170)
WARNING 2023-12-12 16:11:03,740 log 3692 4312 Not Found: /order/
WARNING 2023-12-12 16:11:03,740 basehttp 3692 4312 "GET /order/ HTTP/1.1" 404 2201
WARNING 2023-12-12 16:11:03,838 log 3692 4312 Not Found: /favicon.ico
INFO 2023-12-12 16:11:03,838 basehttp 3692 4312 - Broken pipe from ('127.0.0.1', 51201)
INFO 2023-12-12 16:12:04,466 autoreload 7092 24216 Watching for file changes with StatReloader
INFO 2023-12-12 16:18:38,108 autoreload 12860 14628 Watching for file changes with StatReloader
INFO 2023-12-12 16:43:49,556 autoreload 8920 20312 Watching for file changes with StatReloader
INFO 2023-12-12 16:46:38,841 autoreload 8920 20312 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:46:39,274 autoreload 6992 3064 Watching for file changes with StatReloader
INFO 2023-12-12 16:47:19,170 autoreload 14496 14576 Watching for file changes with StatReloader
INFO 2023-12-12 16:47:22,419 basehttp 14496 19388 "GET /sem3app/ HTTP/1.1" 200 225
WARNING 2023-12-12 16:47:22,576 log 14496 19388 Not Found: /favicon.ico
INFO 2023-12-12 16:47:22,578 basehttp 14496 19388 - Broken pipe from ('127.0.0.1', 52239)
INFO 2023-12-12 16:47:48,099 basehttp 14496 24204 "GET /sem3app/hello2/ HTTP/1.1" 200 23
INFO 2023-12-12 16:48:36,859 autoreload 14496 14576 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:48:37,218 autoreload 20796 15652 Watching for file changes with StatReloader
INFO 2023-12-12 16:49:29,391 autoreload 20796 15652 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:49:29,862 autoreload 13480 4868 Watching for file changes with StatReloader
INFO 2023-12-12 16:53:16,246 autoreload 13480 4868 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:53:16,756 autoreload 13900 6360 Watching for file changes with StatReloader
INFO 2023-12-12 16:59:09,853 autoreload 13900 6360 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 16:59:10,314 autoreload 8264 16268 Watching for file changes with StatReloader
INFO 2023-12-12 16:59:13,577 autoreload 8264 16268 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:59:13,994 autoreload 2116 13184 Watching for file changes with StatReloader
INFO 2023-12-12 16:59:35,438 autoreload 2116 13184 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:59:36,086 autoreload 11652 16380 Watching for file changes with StatReloader
INFO 2023-12-12 16:59:43,556 basehttp 11652 21524 "GET /sem3app/hello/ HTTP/1.1" 200 26
INFO 2023-12-12 16:59:49,615 autoreload 11652 16380 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 16:59:50,099 autoreload 15860 23684 Watching for file changes with StatReloader
INFO 2023-12-12 17:01:59,592 autoreload 15860 23684 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:01:59,974 autoreload 17332 17192 Watching for file changes with StatReloader
INFO 2023-12-12 17:02:26,543 autoreload 17332 17192 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:02:27,206 autoreload 9292 24180 Watching for file changes with StatReloader
INFO 2023-12-12 17:04:07,103 autoreload 9292 24180 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:04:07,532 autoreload 2900 11548 Watching for file changes with StatReloader
INFO 2023-12-12 17:04:20,950 autoreload 2900 11548 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:04:21,569 autoreload 21012 5812 Watching for file changes with StatReloader
INFO 2023-12-12 17:07:02,614 autoreload 21012 5812 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:07:03,176 autoreload 10964 21948 Watching for file changes with StatReloader
INFO 2023-12-12 17:07:16,591 autoreload 10964 21948 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:07:17,098 autoreload 1936 21840 Watching for file changes with StatReloader
INFO 2023-12-12 17:07:24,381 autoreload 1936 21840 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 17:07:24,849 autoreload 4632 21908 Watching for file changes with StatReloader
WARNING 2023-12-12 17:08:26,693 log 4632 12712 Not Found: /les3/posts/2022/6/python/
WARNING 2023-12-12 17:08:26,694 basehttp 4632 12712 "GET /les3/posts/2022/6/python/ HTTP/1.1" 404 2258
WARNING 2023-12-12 17:08:26,772 log 4632 12712 Not Found: /favicon.ico
WARNING 2023-12-12 17:08:26,773 basehttp 4632 12712 "GET /favicon.ico HTTP/1.1" 404 2216
INFO 2023-12-12 17:09:18,291 autoreload 4632 21908 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:09:18,769 autoreload 19204 18740 Watching for file changes with StatReloader
INFO 2023-12-12 17:09:25,960 basehttp 19204 23320 "GET /sem3app/hello/ HTTP/1.1" 200 26
WARNING 2023-12-12 17:09:26,092 log 19204 23320 Not Found: /favicon.ico
INFO 2023-12-12 17:09:26,094 basehttp 19204 23320 - Broken pipe from ('127.0.0.1', 53110)
INFO 2023-12-12 17:15:33,526 autoreload 19204 18740 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 17:15:34,011 autoreload 21520 22932 Watching for file changes with StatReloader
INFO 2023-12-12 17:15:53,780 basehttp 21520 11212 "GET /sem3app/user_year/2023 HTTP/1.1" 301 0
INFO 2023-12-12 17:15:53,831 basehttp 21520 24964 "GET /sem3app/user_year/2023/ HTTP/1.1" 200 29
INFO 2023-12-12 17:18:50,999 autoreload 21520 22932 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:18:51,522 autoreload 7500 17100 Watching for file changes with StatReloader
INFO 2023-12-12 17:19:02,984 basehttp 7500 4496 "GET /sem3app HTTP/1.1" 301 0
INFO 2023-12-12 17:19:03,022 basehttp 7500 10344 "GET /sem3app/ HTTP/1.1" 200 210
WARNING 2023-12-12 17:19:03,100 log 7500 10344 Not Found: /favicon.ico
INFO 2023-12-12 17:19:03,116 basehttp 7500 10344 - Broken pipe from ('127.0.0.1', 53404)
WARNING 2023-12-12 17:19:37,008 log 7500 5208 Not Found: /sem3app/admin/
WARNING 2023-12-12 17:19:37,008 basehttp 7500 5208 "GET /sem3app/admin/ HTTP/1.1" 404 3308
WARNING 2023-12-12 17:42:55,335 log 7500 20896 Not Found: /sem3app/my_view
WARNING 2023-12-12 17:42:55,335 basehttp 7500 20896 "GET /sem3app/my_view HTTP/1.1" 404 3311
INFO 2023-12-12 17:43:01,161 autoreload 7500 17100 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 17:43:01,657 autoreload 15488 23244 Watching for file changes with StatReloader
INFO 2023-12-12 17:43:17,036 autoreload 15488 23244 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:43:17,470 autoreload 584 22732 Watching for file changes with StatReloader
INFO 2023-12-12 17:43:20,242 basehttp 584 10004 "GET /sem3app/my_view HTTP/1.1" 301 0
ERROR 2023-12-12 17:43:20,315 log 584 16432 Internal Server Error: /sem3app/my_view/
Traceback (most recent call last):
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\sem3\sem3app\views.py", line 89, in my_view
    return render(request, "myapp3/my_template.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: myapp3/my_template.html
ERROR 2023-12-12 17:43:20,332 basehttp 584 16432 "GET /sem3app/my_view/ HTTP/1.1" 500 79303
WARNING 2023-12-12 17:43:20,427 log 584 16432 Not Found: /favicon.ico
INFO 2023-12-12 17:43:20,427 basehttp 584 16432 - Broken pipe from ('127.0.0.1', 54085)
INFO 2023-12-12 17:44:29,089 autoreload 584 22732 D:\GB\TASKS\Django\sem3\sem3app\views.py changed, reloading.
INFO 2023-12-12 17:44:29,459 autoreload 5456 15856 Watching for file changes with StatReloader
ERROR 2023-12-12 17:44:31,831 log 5456 15740 Internal Server Error: /sem3app/my_view/
Traceback (most recent call last):
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\sem3\sem3app\views.py", line 89, in my_view
    return render(request, "sem3app/index_sem3app.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sem3app/index_sem3app.html
ERROR 2023-12-12 17:44:31,831 basehttp 5456 15740 "GET /sem3app/my_view/ HTTP/1.1" 500 79357
WARNING 2023-12-12 17:44:31,915 log 5456 15740 Not Found: /favicon.ico
INFO 2023-12-12 17:44:31,915 basehttp 5456 15740 - Broken pipe from ('127.0.0.1', 54142)
INFO 2023-12-12 17:46:55,167 basehttp 5456 440 "GET /sem3app/ HTTP/1.1" 200 210
WARNING 2023-12-12 17:46:55,273 log 5456 440 Not Found: /favicon.ico
INFO 2023-12-12 17:46:55,273 basehttp 5456 440 - Broken pipe from ('127.0.0.1', 54200)
WARNING 2023-12-12 17:47:02,597 log 5456 3884 Not Found: /
WARNING 2023-12-12 17:47:02,597 basehttp 5456 3884 "GET / HTTP/1.1" 404 2165
WARNING 2023-12-12 17:47:10,828 log 5456 3884 Not Found: /favicon.ico
INFO 2023-12-12 17:47:10,828 basehttp 5456 3884 - Broken pipe from ('127.0.0.1', 54206)
ERROR 2023-12-12 17:48:12,424 log 5456 5700 Internal Server Error: /sem3app/my_view/
Traceback (most recent call last):
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\sem3\sem3app\views.py", line 89, in my_view
    return render(request, "sem3app/index_sem3app.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sem3app/index_sem3app.html
ERROR 2023-12-12 17:48:12,424 basehttp 5456 5700 "GET /sem3app/my_view/ HTTP/1.1" 500 79357
WARNING 2023-12-12 17:48:12,520 log 5456 5700 Not Found: /favicon.ico
INFO 2023-12-12 17:48:12,536 basehttp 5456 5700 - Broken pipe from ('127.0.0.1', 54235)
INFO 2023-12-12 17:48:25,628 autoreload 5456 15856 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 17:48:26,070 autoreload 16000 10080 Watching for file changes with StatReloader
ERROR 2023-12-12 17:48:28,644 log 16000 10884 Internal Server Error: /sem3app/my_view/
Traceback (most recent call last):
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\sem3\sem3app\views.py", line 89, in my_view
    return render(request, "sem3app/index_sem3app.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GB\TASKS\Django\.virt\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: sem3app/index_sem3app.html
ERROR 2023-12-12 17:48:28,660 basehttp 16000 10884 "GET /sem3app/my_view/ HTTP/1.1" 500 79357
WARNING 2023-12-12 17:48:28,762 log 16000 10884 Not Found: /favicon.ico
INFO 2023-12-12 17:48:28,762 basehttp 16000 10884 - Broken pipe from ('127.0.0.1', 54247)
INFO 2023-12-12 17:49:42,985 autoreload 16000 10080 D:\GB\TASKS\Django\sem3\sem3app\urls.py changed, reloading.
INFO 2023-12-12 17:49:43,422 autoreload 22120 17760 Watching for file changes with StatReloader
INFO 2023-12-12 17:49:45,749 basehttp 22120 10544 "GET /sem3app/my_view/ HTTP/1.1" 200 178
WARNING 2023-12-12 17:49:45,838 log 22120 10544 Not Found: /favicon.ico
INFO 2023-12-12 17:49:45,838 basehttp 22120 10544 - Broken pipe from ('127.0.0.1', 54284)
